server:
  port: 8080

grpc:
  server:
    port: 3100

# Oracle Database Connection
database:
  primary:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: root
    password: 123456
    timeout: 60000
    maximum-pool-size: 10

# Virtual Threads
spring:
  threads:
    virtual:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
