server:
  port: 8080

grpc:
  server:
    port: 3100

database:
  primary:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: root
    password: 123456
    timeout: 60000
    maximum-pool-size: 10
spring:
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
#    hibernate:
#      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
